feat(components): add divider component, use divider component to divide posts and comments #206
kamp-us/monorepo pull request #228
Opened 2023-02-24 23:14 UTC by andyanday33

Fixes #206: divides comments and post(s)

![Screenshot 2023-02-24 at 23 11 53](https://user-images.githubusercontent.com/31995815/221319040-a94eb729-7876-4a2d-b124-4cc4200e7b22.png)

2023-02-25 00:11 UTC, cansirin commented
Thank you so much for your contribution @andyanday33!

We are using Radix UI for our component needs and this UI kit has a "separator" component like this here: https://www.radix-ui.com/docs/primitives/components/separator

Can we please update this PR with this component?

2023-02-25 00:38 UTC, andyanday33 commented
> Thank you so much for your contribution @andyanday33!
> 
> We are using Radix UI for our component needs and this UI kit has a "separator" component like this here: https://www.radix-ui.com/docs/primitives/components/separator
> 
> Can we please update this PR with this component?

I have updated Posts/$slug-$id page to use a styled component extending Radix UI Separator.

2023-02-25 22:45 UTC, cansirin requested changes

2023-02-26 01:16 UTC, usirin approved these changes

2023-02-26 01:17 UTC, cansirin approved these changes

2023-02-26 01:18 UTC, merged

2023-02-26 01:39 UTC, andyanday33 commented
Apparently, it works without a parent component with width set to 100%

![Screenshot 2023-02-26 at 01 24 47](https://user-images.githubusercontent.com/31995815/221387661-fb96dbe7-e82c-4e09-b57a-895d67a73550.png)