feat(@kampus/pano-button & @kampus/pano): Create an embeddable share component
kamp-us/monorepo pull request #345
Opened 2023-03-21 03:46 UTC by andyanday33

# Description

I have created a new package containing a share button, that could be embedded in websites to point out to send route of pano with a prefilled URL value.
I have also added a query 

### Checklist

- [X] discord username: `bumshaqalaqa#2973`
- [X] Closes #310 
- [X] PR must be created for an issue from issues under "In progress" column from [our project board](https://github.com/orgs/kamp-us/projects/2/views/1).
- [X] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules, and should include the app/package/service name in the title. For example, a title like "docs(@kampus-apps/pano): Add README.md" can be used.
- [X] Related file selection: Only relevant files should be touched and no other files should be affected.
- [X] I ran `npx turbo run` at the root of the repository, and build was successful.
- [X] I installed the npm packages using `npm install --save-exact <package>` so my package is pinned to a specific npm version. Leave empty if no package was installed. Leave empty if no package was installed with this PR.

### How were these changes tested?

I have added a temporary share button to the settings page, imported it from @kampus/pano-button package, and provided the component a URL value, then tested it manually.

2023-03-21 23:06 UTC, usirin commented on packages/pano-button/README.md
> +Embeddable share button for kampus apps.
[NIT] for pano, not kampus apps 😅

2023-03-21 23:21 UTC, usirin requested changes

2023-03-21 23:21 UTC, usirin commented on apps/pano/app/routes/send.tsx
> +    if (queryUrl) fetchMetaTags(queryUrl);
let's move this to `loader` and return it from there, that way we can ensure that the values are actually generated on the server. then component can use the loader data as inputs' default values.

2023-03-21 23:21 UTC, usirin commented on packages/pano-button/src/ShareButton.tsx
> +  return <Button onClick={handleClick}>Share this on kamp-us pano</Button>;
Let's use turkish here.

2023-03-28 04:30 UTC, usirin commented
@andyanday33 ping pong

2023-03-30 01:59 UTC, andyanday33 commented
> @andyanday33 ping pong

sorry, gonna work on this tomorrow.

2023-04-01 01:23 UTC, andyanday33 commented
Updated regarding changes suggested

2023-04-01 02:39 UTC, andyanday33 commented
currently, the default value of title input does not change on paste or blur when the query parameter "url" exists for some reason, it requires further investigation.

2023-04-08 23:26 UTC, usirin approved these changes

2023-04-08 23:26 UTC, merged